Repository Daniel-Velasco-Lopez/P-gina-Web, pull requests merged in 2025-03, with the labels that each got.

#2 PR_Kimberly
  .vscode/settings.json
  CSS/estilos.css
  Img/Logo.png
  index.html
Labels: bug

#3 PR_Realase
  .vscode/settings.json
  CSS/estilos.css
  Img/Logo.png
  index.html
Labels: documentation, duplicate

#4 PR_Realase
  .vscode/settings.json
  CSS/estilos.css
  Img/Logo.png
  index.html
Labels: bug, documentation

#5 PR_Realase
  .vscode/settings.json
  CSS/estilos.css
  Img/Logo.png
  index.html
Labels: bug, documentation

#6 PR_Realase
  .vscode/settings.json
  CSS/estilos.css
  Img/Logo.png
  index.html
Labels: bug, documentation

#7 PR_Realase
  index.html
Labels: bug, documentation

#9 PR_Se agrego la introduccion de la pagina y los estilos de lo antes mencionado
  CSS/estilos.css
  index.html
Labels: Front-end

#10 PR_Realase
  CSS/estilos.css
  index.html
Labels: bug, documentation

#11 Realase
  .vscode/settings.json
  CSS/estilos.css
  Img/Logo.png
  index.html
Labels: bug, documentation

#12 PR_Agregue botones
  CSS/estilos.css
  index.html
Labels: Front-end

#13 PR_Realase
  CSS/estilos.css
  index.html
Labels: bug, documentation

#14 PR_Agregue Imagen y le di estilo
  CSS/estilos.css
  Img/CafeTradicional.jpg
  index.html
Labels: Front-end

#15 PR-Realase
  CSS/estilos.css
  Img/CafeTradicional.jpg
  index.html
Labels: documentation

#16 PR_Agregue Carrusel
  CSS/estilos.css
  Img/cafe1.jpg
  Img/cafe2.jpg
  Img/cafe3.jpg
  Img/cafe4.jpg
  Img/cafe5.jpg
  index.html
Labels: Front-end

#17 PR-Realase
  CSS/estilos.css
  Img/CafeTradicional.jpg
  Img/cafe1.jpg
  Img/cafe2.jpg
  Img/cafe3.jpg
  Img/cafe4.jpg
  Img/cafe5.jpg
  index.html
Labels: bug, documentation

#18 PR_Realizando Caja de Comentarios
  index.html
Labels: Front-end

#19 PR_Realase
  CSS/estilos.css
  Img/CafeTradicional.jpg
  Img/cafe1.jpg
  Img/cafe2.jpg
  Img/cafe3.jpg
  Img/cafe4.jpg
  Img/cafe5.jpg
  index.html
Labels: bug, documentation

#20 PR_Realase
  CSS/estilos.css
  Img/CafeTradicional.jpg
  Img/cafe1.jpg
  Img/cafe2.jpg
  Img/cafe3.jpg
  Img/cafe4.jpg
  Img/cafe5.jpg
  index.html
Labels: documentation, duplicate

#21 PR_Marlene
  CSS/estilos.css
  Img/facebook.png
  Img/instagram.png
  Img/x.png
  index.html
Labels: Front-end

#22 PR_Realase
  CSS/estilos.css
  Img/facebook.png
  Img/instagram.png
  Img/x.png
  index.html
Labels: bug, documentation

#23 PR_Realase
  CSS/estilos.css
  Img/facebook.png
  Img/instagram.png
  Img/x.png
  index.html
Labels: bug, documentation

#24 PR_Edgar
  CSS/estilos.css
  index.html
Labels: Front-end

#26 PR_Realase
  CSS/estilos.css
  Img/cafe1.jpg
  Img/cafe2.jpg
  Img/cafe3.jpg
  Img/cafe4.jpg
  Img/cafe5.jpg
  Img/facebook.png
  Img/instagram.png
  Img/x.png
  index.html
Labels: documentation

#27 PR-Realase
  CSS/estilos.css
  Img/facebook.png
  Img/instagram.png
  Img/x.png
  index.html
Labels: documentation

#28 PR_Realase
  CSS/estilos.css
  Img/CafeTradicional.jpg
  Img/cafe1.jpg
  Img/cafe2.jpg
  Img/cafe3.jpg
  Img/cafe4.jpg
  Img/cafe5.jpg
  Img/facebook.png
  Img/instagram.png
  Img/x.png
  index.html
Labels: bug, documentation

#29 PR_Realase
  CSS/estilos.css
  index.html
Labels: documentation, duplicate

#30 PR_Realase
  CSS/estilos.css
  Img/CafeTradicional.jpg
  Img/cafe1.jpg
  Img/cafe2.jpg
  Img/cafe3.jpg
  Img/cafe4.jpg
  Img/cafe5.jpg
  Img/facebook.png
  Img/instagram.png
  Img/x.png
  index.html
Labels: bug, documentation

#31 PR_Realase
  .vscode/settings.json
  CSS/estilos.css
  Img/CafeTradicional.jpg
  Img/Logo.png
  Img/cafe1.jpg
  Img/cafe2.jpg
  Img/cafe3.jpg
  Img/cafe4.jpg
  Img/cafe5.jpg
  Img/facebook.png
  Img/instagram.png
  Img/x.png
  index.html
Labels: documentation
